version: 2.1
jobs:
  build-lambda-zips:
    docker:
      - image: circleci/python:3.7.0
    working_directory: /tmp/workspace
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Build Lambda function
          command: |
            lambda_dir=~/repo/src
            test -d "$lambda_dir" || exit 1
            (
              cd "$lambda_dir"
              if [ -e "./ci_prepare.sh" ]; then
                printf "Running ./ci_prepare.sh\n"
                bash "./ci_prepare.sh" || { printf "CI preparation script failed\n" && exit 1; }
                printf "Successfully ran CI preparation script\n"
              fi
            )
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-lambda-zip:
          filters:
            branches:
              only:
                - master
